((computed
  (("Accidental Shot" ()) ("Act Together" ()) ("Affix a Fulu" ()) (Anchor ())
   ("Arcane Cascade" ()) ("Armor Up!" ()) ("Banshee Cry" ())
   ("Basic Finisher" ()) ("Beast's Charge" ()) ("Bend Time" ())
   ("Boarding Assault" ()) ("Breath Weapon (Acid) (Cone)" ())
   ("Breath Weapon (Acid) (Line)" ()) ("Breath Weapon (Cold) (Cone)" ())
   ("Breath Weapon (Cold) (Line)" ())
   ("Breath Weapon (Electricity) (Cone)" ())
   ("Breath Weapon (Electricity) (Line)" ())
   ("Breath Weapon (Fire) (Cone)" ()) ("Breath Weapon (Fire) (Line)" ())
   ("Breath Weapon (Negative) (Cone)" ())
   ("Breath Weapon (Negative) (Line)" ())
   ("Breath Weapon (Piercing) (Cone)" ())
   ("Breath Weapon (Piercing) (Line)" ())
   ("Breath Weapon (Poison) (Cone)" ()) ("Breath Weapon (Poison) (Line)" ())
   ("Bullet Dancer Stance" ()) ("Call Gun" ()) ("Cast a Spell" ())
   (Catharsis ()) ("Change Shape (Anadi)" ()) ("Change Shape (Beastkin)" ())
   ("Change Shape (Kitsune)" ()) ("Cleanse Soul Path" ()) ("Clear a Path" ())
   ("Conjure Bullet" ()) ("Coughing Dragon" ()) ("Covered Reload" ())
   ("Defend Life" ()) ("Dispelling Bullet" ()) ("Divert Lightning" ())
   ("Draconic Frenzy" ()) ("Dream Research" ()) ("Drifter's Wake" ())
   ("Dutiful Retaliation" ()) ("Encouraging Words" ()) ("Energy Shot" ())
   (Explode ()) ("Fey's Fortune" ()) ("Field of Roots" ())
   ("Fight with Fear" ()) ("Finish The Job" ()) (Foresight ())
   ("Furious Strike" ()) ("Ghost Shot" ()) ("Goblin Jubilee" ())
   ("Grim Swagger" ()) ("Instinctive Obfuscation" ()) (Interact ())
   ("Into the Fray" ()) ("Jumping Jenny" ()) ("Launch Fireworks Display" ())
   ("Learn Name" ()) ("Life Block" ()) ("Living Fortification" ())
   ("Manifest Eidolon" ()) ("Manifest Soulforged Armament" ())
   ("Mist Blending" ()) (Overdrive ()) ("Overload Vision" ())
   ("Pistolero's Retort" ()) ("Primal Roar" ()) ("Prophecy's Pawn" ())
   ("Raconteur's Reload" ()) ("Rampaging Ferocity" ())
   ("Recall Ammunition" ()) ("Reloading Strike" ()) ("Salt Wound" ())
   ("Seething Frenzy" ()) ("Set Explosives" ()) ("Settle Emotions" ())
   ("Sever Conduit" ()) ("Share Life" ()) ("Share Senses" ())
   ("Shootist's Draw" ()) (Siegebreaker ()) ("Smoke Blending" ())
   ("Soaring Flight" ()) (Spellsling ()) (Spellstrike ())
   ("Spinning Crush" ()) ("Steel your Resolve" ()) ("Tap Ley Line" ())
   ("Tendril Strike" ()) ("That's My Number" ()) ("Thoughtful Reload" ())
   ("Thundering Roar" ()) ("Visions of Sin" ()) ("Vital Shot" ())
   ("Warding Sign" ()) ("Whirlwind Maul" ()) ("Wish for Luck" ())
   ("Wyrm's Breath" ())))
 (manual ()))
